.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH 8bitx 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B 8bitx 
.SH SYNOPSIS
.B 8bitx x-windowsprogram
.SH DESCRIPTION
.B 8bitx
is a zsh template function created to run a program in an 8-bit (256 colors) X11 display
without disturbing the default 24-bit X11. It uses Xquartz and thus requires Apple's X11
to be installed.
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR Xquartz (1)


