.TH _edit 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B _edit
\- completion function for the function edit my_prefs_edit function to define default gui editors for use in the edit and hydra functions my_prefs_edit helper function for local edit and hydra functions; assists in setting default apps _cns_edit completion function for cns_edit cns_edit function to edit cns files using web browser interface (crystallography)

.SH SYNOPSIS
_edit

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
