.TH _fink 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B _fink
\- completion function for the function replacing the command fink _fink_web completion function for the function fink_web

.SH SYNOPSIS
_fink

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
