.TH _guidirs 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B _guidirs
\- helper function for the command gdirs _guidirs.zsh helper script for the command gdirs in pashua mode _guidirs_pashua helper script for the command gdirs in pashua mode _guidirs function wrapped by gdirs (use gdirs to call it)

.SH SYNOPSIS
_guidirs

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
