.TH _mac_applications 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B _mac_applications
\- helper function for _open and open functions my_mac_applications helper function for _open, i.e., "open -a" completions

.SH SYNOPSIS
_mac_applications

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
