.TH _switch_users 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B _switch_users
\- completion function for the function switch_users (command-line fast user switching)

.SH SYNOPSIS
_switch_users

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
