.TH _users 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B _users
\- completion function for the function switch_users (command-line fast user switching) _users completion function for only the real users in /Users directory switch_users function to do fast user switching from the command line (eg: switch_users nixon )

.SH SYNOPSIS
_users

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
