.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH a2preview 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B a2preview 
.SH SYNOPSIS
.B a2preview ascii-text-file
.SH DESCRIPTION
.B a2preview is a wrapper for a2ps that makes an ascii text file into a pretty pdf. You have
to install a2ps (for example with fink).
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR a2ps (1)


