.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH a2psrc 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B a2psrc 
.SH SYNOPSIS
.B a2psrc
.SH DESCRIPTION
.B a2psrc
is an rc file for a2ps. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR a2ps (1),
.BR a2preview (7)


