.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH addIcon 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B addIcon 
.SH SYNOPSIS
.B addIcon imagefilename[s]
.SH DESCRIPTION
.B addIcon
invokes /usr/bin/sips --addIcon to put an icon on an image file, and can batch process a whole pile of images.
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR sips (1)


