.TH ccp4help 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B ccp4help
\- function to open browser to named ccp4 document (eg: ccp4help mlphare) (crystallography)

.SH "SEE ALSO"
.BR ccp4 (1)

.SH SYNOPSIS
ccp4help [programname]

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
