.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH cdt 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B cdt 
.SH SYNOPSIS
.B cdt [-f,-F]
.SH DESCRIPTION
.B cdt
change the current working directory to that corresponding to the file displayed in TextMate's frontmost window

.B cdt -F
change this and the Finder (-F)

.B cdt -f
change the finder only (-f)

This is only useful if you are using the text editing program 
.B TextMate.app.
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR cdt (1)


