.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH cns_web 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B cns_web 
.SH SYNOPSIS
.B cns_web
.SH DESCRIPTION
.B cns_web
invokes the cns_web function from CNS is an OSX-friendly browser. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR cns (7)


