.TH cns_solve 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B cns_solve
\- function to run the crystallography and NMR program cns_solve (crystallography) 

.SH SYNOPSIS
cns_solve < 
.I inputfile.inp
.B [
> 
.I outputfile.log
.B ]
&

.SH SEE ALSO
Issue the command
.B cns_web
for full documentation and to access the GUI interface.

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
