.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH configure_zsh_templates 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B configure_zsh_templates 
.SH SYNOPSIS
.B configure_zsh_templates
.SH DESCRIPTION
.B configure_zsh_templates
invokes the configure_zsh_templates gui function to assist in configuring the zsh shell customization templates. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR zsh-templates (7)


