.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH configure_zsh_templates_asgui 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B configure_zsh_templates_asgui 
.SH SYNOPSIS
.B configure_zsh_templates_asgui
.SH DESCRIPTION
.B configure_zsh_templates_asgui
is invoked by the configure_zsh_templates function. It invokes the Applescript GUI version useful for small displays.
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR configure_zsh_templates (7)


