.\"
.TH "customize_x11" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B customize_x11
\- Assist the user in changing (improving) the behavior of Apple's X11.app

.SH SYNOPSIS

customize_x11

.SH DESCRIPTION

.B customize_x11
is an interactive shell script that assists the user in changing settings that
govern the behavior of X11.  It prompts the user before making any change, and
explains the options carefully.

.B customize_x11
will ask the user if X11 should be added to the user's startup items, whether focus follows
mouse behavior (emulating canonical X11 unix systems) should be set, whether the user should
be warned on logout if X11 is running, whether X11 should be run as a dockless and menuless
application in the background, as so forth.  Re-running the function will permit the user to
restore default behaviors.


.SH AUTHOR
William Scott  

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
