.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH da2preview 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B da2preview 
.SH SYNOPSIS
.B da2preview [asciitext filename]
.SH DESCRIPTION
.B da2preview
invokes the a2preview function in double-column output mode. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR a2preview (7)


