.\"
.TH "delete_user" 7 "August 4, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B delete_user
\- Delete a user from the Directory Service database and archive's the user's account

.SH SYNOPSIS

delete_user username

.SH DESCRIPTION  

.B delete_user
Consider using the System Preferences > Accounts preference pane to do this instead.

The 
.B delete_user
command must be invoked by an admin user.

Takes the account name (short name) and:

removes the user from all groups

removes the user's primary group (of the same name)

removes the user's account in NetInfo

archives and deletes the user's home directory in /Users/shortname



.SH SEE ALSO
.BR add_user(7),
.BR addgroup(7),
.BR delete_user(7),
.BR delete_group(7),
.BR remove_user_from_group(7),
.BR adduser2group(7)
                        

.SH AUTHOR
Obtained and modified from a bash shell script available at
http://www.osxfaq.com/tips/unix-tricks/week91/friday.ws

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
