.\"
.TH "delete_group" 7 "August 4, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B delete_group
\- Delete a group from the Directory Service database

.SH SYNOPSIS

delete_group groupname

.SH DESCRIPTION  

.B delete_group
Takes the user group name and deletes it from NetInfo
This function must be run as a root user


.SH SEE ALSO
.BR add_user(7),
.BR addgroup(7),
.BR delete_user(7),
.BR delete_group(7),
.BR remove_user_from_group(7),
.BR adduser2group(7)
                        

.SH AUTHOR
Obtained and modified from a bash shell script available at
http://www.osxfaq.com/tips/unix-tricks/week91/friday.ws

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
