.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH disable_Dashboard 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B disable_Dashboard 
.SH SYNOPSIS
.B disable_Dashboard
.SH DESCRIPTION
.B disable_Dashboard
invokes the disable_Dashboard function that disables the annoying memory-hog Apple Dashboard and its associated
collection of vile widgets.
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR enable_Dashboard (7)
 


