.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH empty_trash 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B empty_trash 
.SH SYNOPSIS
.B empty_trash
.SH DESCRIPTION
.B empty_trash
empties the Apple trash can. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR rm (1)


