.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH enable_Dashboard 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B enable_Dashboard 
.SH SYNOPSIS
.B enable_Dashboard
.SH DESCRIPTION
.B enable_Dashboard
the inverse of the disable_Dashboard function. Restores those stupid widgets.
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR disable_Dashboard (7)


