.\"
.TH "enable_faster_open" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B enable_faster_open
\- Assist the user in improving the speed of 
.B open -a 
completions          

.SH SYNOPSIS

enable_faster_open

.SH DESCRIPTION

.B enable_faster_open
Run this function to optimize the behavior of the open -a completion function.

.SH AUTHOR
William Scott  

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
