.TH fds 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B fds
\- function to issue find / -name "${1}" -print 2>/dev/null 

.SH SEE ALSO
.B fdsa 
function to issue fds for all files

.SH SYNOPSIS
fds

.SH AUTHOR
Gary Kerbaugh 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
