.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH find_dups 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B find_dups 
.SH SYNOPSIS
.B find_dups
.SH DESCRIPTION
.B find_dups
will find duplicate files on specified directory tree
.SH AUTHOR
 Karl Zimmerman  
.SH "SEE ALSO"
.BR find (1)


