.\"
.TH "finder_update" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B finder_update
\- refresh a Finder.app window's display and contents

.SH SYNOPSIS
finder_update

.SH DESCRIPTION

.B finder_update
function to update desktop and all open Finder windows

.SH AUTHOR
Wataru Kagawa 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
