.\"
.TH "fink_web" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B fink_web
\- search the fink package website database

.SH SYNOPSIS
fink_web [packagename]

fink_web -s PATTERN

.SH DESCRIPTION

.B fink_web 
is a function to search fink's package website database.  It takes a fink packagename as an
optional argument, eg:  fink_web zsh-templates.  If the 
.B -s
option is invoked, a search is performed to match 
.B PATTERN


.SH AUTHOR
William Scott

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
