.TH fix_namot 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B fix_namot
\- function to fix the buggy pdb files output by namot (nucleic acid modelling program)

.SH SYNOPSIS
fix_namot namot_output.pdb

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
