.\"
.TH "frameerrnum" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B frameerrnum
\- function that greps all of the framework header files for numbers associated with error messages

.SH SYNOPSIS
frameerrnum
.I errornumber

.SH DESCRIPTION

.B frameerrnum
function that greps all of the framework header files for numbers associated with error messages

.SH AUTHOR
Gary Kerbaugh

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
