.\"
.TH "function_key_toggle" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B function_key_toggle
\- Activate or inactivate the function keys.

.SH SYNOPSIS
function_key_toggle

.SH DESCRIPTION

.B function_key_toggle
is a function to 
activate the function keys on a laptop or similar keyboard, where the "fn" or similar
key turns the function keys on and off.  Issuing the command multiple times toggles the
function keys on and off.

.SH AUTHOR
William Scott, based on an OS X hints applescript

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
