.TH gvim 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B gvim
\- function to augment behavior of the command gvim with sudo

.SH SYNOPSIS
gvim

.SH "SEE ALSO"
.BR vim (1)
.BR gvim (1)
.BR vi (1)

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
