.TH help_zsh_templates 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B help_zsh_templates
\- function to open the zsh_templates web site in your default browser

.SH SYNOPSIS
help_zsh_templates

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
