.TH help_template_functions 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B help_template_functions
\- function to obtain simple one-line help for individual functions

.SH OBSOLETE
use 
.B man function_name

.SH SYNOPSIS
help_template_functions function_name

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
