.TH joinpdf 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B joinpdf
\- function to catenate pdf files, produces a file called
.I merged.pdf 
as output.

.SH SYNOPSIS
joinpdf file1.pdf file2.pdb [file3.pdf ...]

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
