.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH killit 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B killit 
\-  obsolete. Use "killall"
.SH SYNOPSIS
.B killit
.SH DESCRIPTION
.B killit
poor man's version of 
.B killall. Kills a process by name.
.SH AUTHOR
 Gary Kerbaugh 
.SH "SEE ALSO"
.BR killall (1)


