.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH make_transparent 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B make_transparent 
\-  uses ImageMagick
.SH SYNOPSIS
.B make_transparent
.SH DESCRIPTION
.B make_transparent
invokes 
.B convert 
from 
.B ImageMagick 
to make an image transparent. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR convert (1)


