.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH mapcover 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B mapcover 
\-  requires CCP4 to be installed
.SH SYNOPSIS
.B mapcover [prefix-mtz-pdb]
.SH DESCRIPTION
.B mapcover
produces a 2Fo-Fc map that covers a specified molecule. The argument must be one in which
both the mtz file and the pdb file share a common prefix (as with the output of refmac or
phenix). 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR mapcoverdiff (7),
.BR mapmask,
.BR fft,
.BR refmac5


