.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH mlocate 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B mlocate 
\-  invokes mdfind to locate a file
.SH SYNOPSIS
.B mlocate [filename]
.SH DESCRIPTION
.B mlocate
invokes mdfind to locate a given file. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR mdfind (1)


