.TH mos2fobs 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B mos2fobs
\- function to process mosflm mtz file in ccp4 scala, producing Fobs in mtz and cns formats (crystallography)

.SH SYNOPSIS
mos2fobs

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 

.SH "SEE ALSO"
.BR mosflm (1)