.TH my_prefs_edit 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B my_prefs_edit
\- function to define default gui editors for use in the edit and hydra functions my_prefs_edit helper function for local edit and hydra functions; assists in setting default apps

.SH SYNOPSIS
my_prefs_edit

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
