.\"
.TH "mybom" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B mybom
\- lsbom the listed package with the given arguments, i.e.,

lsbom -p sfMUG /Library/Receipts/*"$1"*.pkg/Contents/Archive.bom


.SH AUTHOR
Gary Kerbaugh

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
