.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH newx 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B newx 
.SH SYNOPSIS
.B newx
.SH DESCRIPTION
.B newx x-windowsprogram
#  Function to run an x-windowsprogram in second X11 display
#  without disturbing the default 24-bit X11. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR 8bitx (7),
.BR Xquartz (1)


