.\"
.TH "ntab" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B ntab
\- open a new iTerm tabbed window, optionally with a new directory specified.

.SH SYNOPSIS
ntab [directoryname]

If 
.I directoryname
is not specified, the new session will be opened in the current directory.


.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
