.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH osa_file_browser 7 "October 25, 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B osa_file_browser 
\-  returns the path matching the file chosen with the GUI
.SH SYNOPSIS
.B osa_file_browser
.SH DESCRIPTION
.B  osa_file_browser 
is an osascript embedded in a shell script that returns the path
corresponding to the file selected from the GUI file browser.  Its real value lies in being able to incorporate it as a module for scripting.  Here is a simple example

.B openg,
i.e., 

alias openg='open "$(osa_file_browser)"'

The command
.B openg 
then opens the selected file in the default application.
 
.SH AUTHOR
 William Scott
.SH "SEE ALSO"
.BR osa_direc_browser (7),
.BR osa_display_dialog (7),
.BR osa_choose_list (7)
