.TH overlay 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B overlay
\- function to overlay pdf files (made for crystallographic Patterson maps but may be more
generally useful).

.SH SYNOPSIS
overlay file1.pdf file2.pdf compositefile.pdf

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
