.TH posfind 7 "January 1, 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B posfind
\-  runs find in the path matching that of the frontmost finder window
.SH SYNOPSIS
.B posfind foo

where 
.I foo
is all or a fragment of a filename (the same argument that would be given to the find command).
.SH AUTHOR
 Gary Kerbaugh 
.SH "SEE ALSO"
.BR fdc (7),
.BR cdf (7),
.BR posd (7),
.BR find (1)


