.TH prompt_kerbaugh_setup 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B prompt_kerbaugh_setup
\- function defining Gary Kerbaugh's colorful and highly functional prompt

.SH SYNOPSIS
prompt_kerbaugh_setup

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
