.TH run-help 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B run-help
\- function to get help on zsh functions and builtins (fixed for multiple helpdir entries) 
       
man function to augment man command to use info and zsh command run-help in addition to command man

.SH SYNOPSIS
run-help
.I function_name

.SH SEE ALSO
.BR man(7),
.BR man(1),
.BR info(1)

The 
.B man 
function included with 
.B zsh-templates 
combines
.B run-help
with the conventional
.B man
and
.B info
functionality in order
to augment the man command.

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
