.TH screen 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B screen
\- function to run Darwin's screen command and put "screen $1" in the iTerm tab

.SH "SEE ALSO"
.BR screen (1)

.SH SYNOPSIS
screen

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
