.\"
.TH "scrollspeed" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B scrollspeed
\- set the scroll wheel speed on a mouse using the System Preferences contol panel

.SH SYNOPSIS
scrollspeed
.B [
N
.B ]

.SH DESCRIPTION

.B scrollspeed
changes the mouse scroll wheel speed via System Preferences.
Usage:  scrollspeed N  [where N ranges from 0 (slowest) to 7 (fastest)]


.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
