.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH selectfile 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B selectfile 
.SH SYNOPSIS
.B selectfile filename
.SH DESCRIPTION
.B selectfile
opens a finder window in the directory of the specified file, and selects that file as if it were single-clicked in the Finder. 
.SH AUTHOR
 William Scott 
 


