.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH snotify 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B snotify 
\-  invokes growlnotify
.SH SYNOPSIS
.B snotify command
.SH DESCRIPTION
.B snotify
like gnotify but sticky window must be dismissed manually. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR gnotify (7),
.BR growlnotify (1)


