.\"
.TH "sss" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B sss
\- Start the Screen Saver

.SH DESCRIPTION
Issuing 
.B sss
starts the screen saver.
If screen locking is implemented, the sss command has the effect of locking the screen when it is 
issued, preventing nefarious evildoers from deleting your life's work while you walk the dog.

.SH AUTHOR
William Scott

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
