.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH startwm 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B startwm 
.SH SYNOPSIS
.B startwm [start16, startkde, evilwm, etc]
.SH DESCRIPTION
.B startwm
invokes the named window manager in an Xnest window. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR xnest (1)


