.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH sudo 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B sudo 
\-  invokes sudo
.SH SYNOPSIS
.B sudo command
.SH DESCRIPTION
.B sudo
forces 'sudo zsh' to start root as a loging shell to 
avoid problems with environment clashes, otherwise sudo is treated
normally.
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR sudo (1)


