.\"
.TH "switch_prompt" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B switch_prompt
\- Function to permit the user to switch the prompt easily.

.SH SYNOPSIS

switch_prompt

.SH DESCRIPTION

Offers the user an OS X Applescript gui menu of possible zsh prompts.
Some distributed prompt themes may not work properly without additional fonts.
Other prompt themes accept optional arguments that can be added by editing the
file ~/.zsh/zshprompt after selecting the theme.  The prompt functions are found in the
.B fpath
array.  In addition to the supplied zsh prompt themes, two additional themes, called
"kerbaugh" and "simple" have been added in 
.B zsh-templates.


.SH AUTHOR
William Scott

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
