.\"
.TH "switch_users" 7 "March 19, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B switch_users
\- enables fast user switching from the command line.  An optional argument of another
User's 
.I username
will switch to that user.  If the optional argument is not supplied, the display is rotated
to the login window.

.SH SYNOPSIS

.B switch_users 
[
.B username
]

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net>
