.TH sync_fink 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B sync_fink
\- syncronize the /sw folder on a remote computer
with that of the host computer. 

.SH SYNOPSIS
sync_fink <remote name>     

.SH AUTHOR
 Wataru Kagawa (05/17/05)  

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
