.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH tcmd 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B tcmd 
\-  iTerm function
.SH SYNOPSIS
.B tcmd [command]
.SH DESCRIPTION
.B tcmd
executes a command in the same directory but in a new iTerm tab 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR ntab (7)


