.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH tmpj 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B tmpj 
\-  TextMate auxiliary function.
.SH SYNOPSIS
.B tmpj [TextMate_project_file]
.SH DESCRIPTION
.B tmpj
is a function to open a named TextMate project file given just the file name prefix.  mdfind does the hunting for you. In zsh, it works with the _tmpj completion function.
 
.SH AUTHOR
 William Scott 
 


