.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH unixify_rootfiles 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B unixify_rootfiles 
.SH SYNOPSIS
.B unixify_rootfiles [--undo]
.SH DESCRIPTION
.B unixify_rootfiles
is a function that makes the directories /usr /bin /sbin /private /etc /var /tmp visible in the finder. The --undo argument invokes the inverse behavior. Uses /Developer/Tools/SetFile
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR SetFile (1)


