.TH usf_installer 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B usf_installer
\- function to download and  install USF programs (X-ray crystallography)

.SH SYNOPSIS
usf_installer

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 
