.TH vim 7 "August 5, 2005" "Mac OS X" "Mac OS X Darwin ZSH customization" 
.SH NAME
.B vim
\- function to enable vi(m) to edit files using sudo vi(m) if required

.SH SYNOPSIS
vim

.SH AUTHOR
William Scott 

.SH MAINTAINER
W. G. Scott <wgscott@users.sourceforge.net> 

.SH "SEE ALSO"
.BR vi (1)
.BR vim (1)
.BR gvim (1)