.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH xdldataman 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B xdldataman 
\-  requires CCP4
.SH SYNOPSIS
.B xdldataman
.SH DESCRIPTION
.B xdldataman
invokes the xdldataman command within an Xnest session, thereby working around an Apple X11 bug. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR xdldataman,
.BR Xnest (1)


