.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH xdlmapman 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B xdlmapman 
\-  requires CCP4
.SH SYNOPSIS
.B xdlmapman
.SH DESCRIPTION
.B xdlmapman
invokes the xdlmapman command within an Xnest session, thereby working around an Apple X11 bug. 
.SH AUTHOR
 William Scott 
.SH "SEE ALSO"
.BR xdlmapman,
.BR Xnest (1)


