.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH zipit 7 "July 9 2005" "Mac OS X" "Mac OS X Darwin customization" 
.SH NAME
.B zipit 
\-  invokes zipit
.SH SYNOPSIS
.B zipit
.SH DESCRIPTION
.B zipit [filename]
Use ditto to create zip files with resource forks (now default)
Function authored by Gary Kerbaugh. Updated syntax W G Scott May 4 2007
I have added -V for verbose output.
.SH AUTHOR
 Gary Kerbaugh 
.SH "SEE ALSO"
.BR ditto (1),
.BR zip (1)


