#!/bin/zsh -f

# Force 'sudo zsh' to start root as a loging shell to 
# avoid problems with environment clashes:
function sudo {
if [[ $# == 1 &&  $1 = "zsh" ]]; then
        command sudo /bin/zsh -l
else
        command sudo "$@"
fi
}

