#!/bin/zsh -f

#  FILE NAME  addIcon

#  Uses /usr/bin/sips --addIcon  but preserves the original file creation date.
 
 

version="0.0.1"


###############################################################################
 
#  Created by  on .
#  Copyright (c) . All rights reserved.


#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301
#    USA
#    
#    cf. URL:   http://www.fsf.org/licensing/licenses/gpl.html
#
###############################################################################

  

foreach file in "$@"

  DATESTAMP=$(mdls -name kMDItemFSCreationDate $file | awk '{print $3$4}' | perl -p -e 's|[-,:]||g')

  DATESTAMP2=$(( $DATESTAMP / 100 ))

  /usr/bin/sips --addIcon $file

  touch -t $DATESTAMP2 $file

end
