#!/bin/zsh -f

#-----------------------------------------------
# sync_fink
#
# by Wataru Kagawa (05/17/05)
# wkagawa@jota.gsc.riken.go.jp
#
# syncronize the /sw folder on a remote computer
# with that of the host computer.
#
# USAGE:
# sync_fink <remote name>
#-----------------------------------------------



function sync_fink () {

sudo rsync -az -e ssh /sw $1:/

}



sync_fink "$@"
